google:
  application:
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS}
  pubSub:
    topic: vehicle
spring:
  cloud:
    gcp:
      project-id: white-dynamo-394708

apiUrl: /vehicle.json?key=45d8b3f0
mockaroo:
  api:
    url: https://my.api.mockaroo.com